// frontend/src/components/ChatPanel.tsx
import React, { useState, useRef, useEffect } from "react";
import { Send, Square, Bot, User } from "lucide-react";
import type { Message } from "../hooks/useAgent";
import { marked } from "marked";

interface ChatPanelProps {
  messages: Message[];
  isGenerating: boolean;
  onSendMessage: (query: string) => void;
  onStop: () => void;
}

export const ChatPanel: React.FC<ChatPanelProps> = ({
  messages,
  isGenerating,
  onSendMessage,
  onStop,
}) => {
  const [input, setInput] = useState("");
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isGenerating) return;
    onSendMessage(input);
    setInput("");
  };

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const renderContent = (content: string) => {
    // Synchronously parse markdown to HTML with marked
    const html = marked.parse(content || "", { async: false }) as string;
    return <div dangerouslySetInnerHTML={{ __html: html }} />;
  };

  return (
    <div className="chat-panel flex flex-column h-full">
      <div className="panel-header flex align-items-center justify-content-between">
        <h3 className="panel-title flex align-items-center gap-2">
          <Bot size={18} className="panel-icon" />
          <span>Agent Workspace Chat</span>
        </h3>
        {isGenerating && (
          <button className="stop-btn flex align-items-center gap-1" onClick={onStop}>
            <Square size={12} fill="currentColor" />
            <span>Stop Agent</span>
          </button>
        )}
      </div>

      <div className="chat-messages flex-grow overflow-y-auto p-3">
        {messages.map((msg, idx) => {
          const isAssistant = msg.role === "assistant";
          return (
            <div key={idx} className={`message-wrapper ${msg.role}`}>
              <div className="message-avatar flex align-items-center justify-content-center">
                {isAssistant ? <Bot size={16} /> : <User size={16} />}
              </div>
              <div className="message-bubble flex flex-column">
                <div className="message-sender">{isAssistant ? "Agent" : "User"}</div>
                <div className="message-text">
                  {msg.content ? renderContent(msg.content) : <span className="streaming-cursor">█</span>}
                </div>
              </div>
            </div>
          );
        })}
        {messages.length === 0 && (
          <div className="chat-welcome flex flex-column align-items-center justify-content-center h-full text-center p-4">
            <Bot size={48} className="welcome-logo mb-3" />
            <h2>Welcome to Agentic Codex</h2>
            <p className="text-muted text-sm max-w-sm">
              Ask the agent to perform actions, execute workflows, or call custom tools. Everything streams in real-time.
            </p>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <form className="chat-input-container p-3 flex gap-2" onSubmit={handleSubmit}>
        <input
          type="text"
          className="chat-input flex-grow"
          placeholder="Ask the agent something..."
          value={input}
          onChange={(e) => setInput(e.target.value)}
          disabled={isGenerating}
        />
        <button
          type="submit"
          className="send-btn flex align-items-center justify-content-center"
          disabled={!input.trim() || isGenerating}
        >
          <Send size={16} />
        </button>
      </form>
    </div>
  );
};

// frontend/src/lib/ChatPanel.svelte
<script lang="ts">
  import { Send, Square, Bot, User } from "@lucide/svelte";
  import type { AgentController } from "./agent.svelte.ts";

  let { controller }: { controller: AgentController } = $props();
  let input = $state("");
  let messagesEnd = $state<HTMLDivElement | null>(null);

  // Scroll to bottom on messages updates
  $effect(() => {
    if (controller.messages) {
      messagesEnd?.scrollIntoView({ behavior: "smooth" });
    }
  });

  function handleSubmit(e: Event) {
    e.preventDefault();
    if (!input.trim() || controller.isGenerating) return;
    controller.sendMessage(input);
    input = "";
  }
</script>

<div class="chat-panel flex flex-column h-full">
  <div class="panel-header flex align-items-center justify-content-between">
    <h3 class="panel-title flex align-items-center gap-2">
      <Bot size={18} class="panel-icon" />
      <span>Agent Workspace Chat</span>
    </h3>
    {#if controller.isGenerating}
      <button
        class="stop-btn flex align-items-center gap-1"
        onclick={() => controller.stopGeneration()}
      >
        <Square size={12} fill="currentColor" />
        <span>Stop Agent</span>
      </button>
    {/if}
  </div>

  <div class="chat-messages flex-grow overflow-y-auto p-3">
    {#each controller.messages as msg}
      {@const isAssistant = msg.role === "assistant"}
      <div class="message-wrapper {msg.role}">
        <div
          class="message-avatar flex align-items-center justify-content-center"
        >
          {#if isAssistant}
            <Bot size={16} />
          {:else}
            <User size={16} />
          {/if}
        </div>
        <div class="message-bubble flex flex-column">
          <div class="message-sender">{isAssistant ? "Agent" : "User"}</div>
          <div class="message-text">
            {#if msg.content}
              <!-- eslint-disable-next-line svelte/no-at-html-tags -->
              {@html controller.renderMarkdown(msg.content)}
            {:else}
              <span class="streaming-cursor">█</span>
            {/if}
          </div>
        </div>
      </div>
    {/each}

    {#if controller.messages.length === 0}
      <div
        class="chat-welcome flex flex-column align-items-center justify-content-center h-full text-center p-4"
      >
        <Bot size={48} class="welcome-logo mb-3" />
        <h2>Welcome to Agentic Codex</h2>
        <p class="text-muted text-sm max-w-sm">
          Ask the agent to perform actions, execute workflows, or call custom
          tools. Everything streams in real-time.
        </p>
      </div>
    {/if}
    <div bind:this={messagesEnd}></div>
  </div>

  <form class="chat-input-container p-3 flex gap-2" onsubmit={handleSubmit}>
    <input
      type="text"
      class="chat-input flex-grow"
      placeholder="Ask the agent something..."
      bind:value={input}
      disabled={controller.isGenerating}
    />
    <button
      type="submit"
      class="send-btn flex align-items-center justify-content-center"
      disabled={!input.trim() || controller.isGenerating}
    >
      <Send size={16} />
    </button>
  </form>
</div>
